name: Android Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        override: true
        
    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          rust-lib/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
          
    - name: Add Android targets
      run: |
        rustup target add aarch64-linux-android
        rustup target add armv7-linux-androideabi
        rustup target add x86_64-linux-android
        rustup target add i686-linux-android
        
    - name: Install cargo-ndk
      run: cargo install cargo-ndk
      
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Build Rust library
      run: |
        cd rust-lib
        cargo ndk \
          -t aarch64-linux-android \
          -t armv7-linux-androideabi \
          -t x86_64-linux-android \
          -t i686-linux-android \
          build --release
          
    - name: Copy native libraries
      run: |
        mkdir -p app/src/main/jniLibs/arm64-v8a
        mkdir -p app/src/main/jniLibs/armeabi-v7a
        mkdir -p app/src/main/jniLibs/x86_64
        mkdir -p app/src/main/jniLibs/x86
        
        cp rust-lib/target/aarch64-linux-android/release/libsmart_forward.so app/src/main/jniLibs/arm64-v8a/
        cp rust-lib/target/armv7-linux-androideabi/release/libsmart_forward.so app/src/main/jniLibs/armeabi-v7a/
        cp rust-lib/target/x86_64-linux-android/release/libsmart_forward.so app/src/main/jniLibs/x86_64/
        cp rust-lib/target/i686-linux-android/release/libsmart_forward.so app/src/main/jniLibs/x86/
        
    - name: Make gradlew executable
      run: chmod +x gradlew
        
    - name: Build Android APK
      run: |
        ./gradlew assembleDebug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: smart-forward-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Build Release APK
      run: |
        ./gradlew assembleRelease
        
    - name: Upload Release APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: smart-forward-release
        path: app/build/outputs/apk/release/app-release-unsigned.apk
